In [1]:
import pandas as pd
df_ataques = pd.read_csv('../attacks.csv', encoding = "ISO-8859-1")
df_copy = df_ataques.copy()
df = df_copy.copy()

print(df.columns)
print(df.shape)
display(df.head())

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')
(25723, 24)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN


### 1. detecting and removing corrupt records from the database

### 1.1. null values

In [2]:
print("TOTAL FILAS:", len(df))
df.isnull().sum()

TOTAL FILAS: 25723

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Area                      19876
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

In [3]:
# Columns with majority null values: 'Unnamed: 22','Unnamed: 23'
df= df[df.columns[df.isnull().sum()< 25721]]
display(df)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,...,N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,...,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,...,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,N,14h00,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,...,N,NaN,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.21,2018.05.21,6292.0
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,...,N,15h00,NaN,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.b,2018.05.13.b,6291.0
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,N,NaN,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0
15,2018.05.12,12-May-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,male,M,...,N,11h00,NaN,"B.Jacob, Dispatch Live, 5/12/2018",2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.12,2018.05.12,6288.0
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,male,M,...,N,10h30,Shark involvement not confirmed,"B. Myatt, GSAF",2018.05.09-SharpesBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.09,2018.05.09,6287.0
17,2018.04.30.R,Reported 30-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,female,M,...,N,NaN,NaN,"K. McMurray, TrackingSharks.com",2018.04.30.R-Thailand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.30.R,2018.04.30.R,6286.0
18,2018.04.28.b,28-Apr-2018,2018.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,male,M,...,N,10h40,Tiger shark,Costa Rica Star. 4/28/2018,2018.04.28.b-CostaRica.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.28.b,2018.04.28.b,6285.0
19,2018.04.28.a,28-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Gearys Beach,Surfing,Adam Murray,M,...,N,16h50,NaN,"B. Myatt, GSAF",2018.04.28.a-Murray.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.28.a,2018.04.28.a,6284.0
20,2018.04.25.b,25-Apr-2018,2018.0,Questionable,AUSTRALIA,New South Wales,Lennox Head,Surfing,Matthew Lee,M,...,N,07h00,Questionable,"B. Myatt, GSAF",2018.04.25.b-Lee.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.25.b,2018.04.25.b,6283.0
21,2018.04.25.a,25-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,...,N,09h30,3 m shark,"B.Myatt, GSAF",2018.04.25.a-Bruce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.25.a,2018.04.25.a,6282.0
22,2018.04.24,24-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"South Point, Gracetown",Surfing,Nathan Burch,M,...,N,Afternoon,"White shark, 3.5 m","B. Myatt, GSAF",2018.04.24-Burch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.24,2018.04.24,6281.0
23,2018.04.23,23-Apr-2018,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Madoogali,Fishing,Ahmed Rasheed,M,...,N,21h50,Tiger shark,"K. McMurray, TrackingSharks.com",2018.04.23-Maldives.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.23,2018.04.23,6280.0
24,2018.04.22,22-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,male,M,...,N,09h40,"White shark, 2.5 m","Africa News Agency, 4/22/2018",2018.04.22-PlettenbergBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.22,2018.04.22,6279.0
25,2018.04.19,19-Apr-2018,2018.0,Unprovoked,USA,Hawaii,"Shipwrecks Beach, Keoneloa Bay, Kauai",Body boarding,Dylan McWilliams,M,...,N,NaN,6' shark,"The Garden Island, 4/19/2018",2018.04.19-McWilliams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.19,2018.04.19,6278.0
26,2018.04.15.d,15-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,Werner Danielsen,M,...,N,NaN,Juvenile bull shark,"Straits Times, 4/16/2018",2018.04.15.d-Thailand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.d,2018.04.15.d,6277.0
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,...,NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0
28,2018.04.15.b,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Lefthanders, Margaret River Area",Surfing,Jason Longrass,M,...,N,NaN,NaN,"B.Myatt, GSAF",2018.04.15.b-Longrass.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.b,2018.04.15.b,6275.0
29,2018.04.15.a,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Cobblestones, Margaret River Area",Surfing,Alejandro Travaglini,M,...,N,08h00,NaN,"B.Myatt, GSAF",2018.04.15.a-Travaglini.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.a,2018.04.15.a,6274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25695,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# columns of zeros

df['Case Number'].value_counts()
#len = 6287;  2400 empty rows

# match zeros
print(df[df['Case Number'] == '0']) 

# removing rows with null values from df
df = df[pd.notnull(df['Type'])]
df = df.drop(df.index[-1])
print(len(df))
display(df)

     Case Number Date  Year Type Country Area Location Activity Name Sex   \
6302           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6303           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6304           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6305           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6306           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6307           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6308           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6309           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6310           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6311           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6312           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6313           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6314           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6315           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6316           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6317           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6318           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6319           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6320           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6321           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6322           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6323           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6324           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6325           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6326           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6327           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6328           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6329           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6330           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
6331           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
...          ...  ...   ...  ...     ...  ...      ...      ...  ...  ...
8672           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8673           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8674           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8675           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8676           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8677           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8678           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8679           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8680           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8681           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8682           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8683           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8684           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8685           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8686           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8687           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8688           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8689           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8690           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8691           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8692           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8693           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8694           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8695           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8696           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8697           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8698           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8699           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8700           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN
8701           0  NaN   NaN  NaN     NaN  NaN      NaN      NaN  NaN  NaN

      ... Fatal (Y/N) Time Species  Investigator or Source  pdf href formula  \
6302  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6303  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6304  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6305  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6306  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6307  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6308  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6309  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6310  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6311  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6312  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6313  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6314  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6315  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6316  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6317  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6318  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6319  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6320  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6321  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6322  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6323  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6324  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6325  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6326  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6327  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6328  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6329  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6330  ...         NaN  NaN      NaN                    NaN  NaN          NaN
6331  ...         NaN  NaN      NaN                    NaN  NaN          NaN
...   ...         ...  ...      ...                    ...  ...          ...
8672  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8673  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8674  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8675  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8676  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8677  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8678  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8679  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8680  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8681  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8682  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8683  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8684  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8685  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8686  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8687  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8688  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8689  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8690  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8691  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8692  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8693  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8694  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8695  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8696  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8697  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8698  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8699  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8700  ...         NaN  NaN      NaN                    NaN  NaN          NaN
8701  ...         NaN  NaN      NaN                    NaN  NaN          NaN

     href Case Number.1 Case Number.2 original order
6302  NaN           NaN           NaN         6304.0
6303  NaN           NaN           NaN         6305.0
6304  NaN           NaN           NaN         6306.0
6305  NaN           NaN           NaN         6307.0
6306  NaN           NaN           NaN         6308.0
6307  NaN           NaN           NaN         6309.0
6308  NaN           NaN           NaN         6310.0
6309  NaN           NaN           NaN            NaN
6310  NaN           NaN           NaN            NaN
6311  NaN           NaN           NaN            NaN
6312  NaN           NaN           NaN            NaN
6313  NaN           NaN           NaN            NaN
6314  NaN           NaN           NaN            NaN
6315  NaN           NaN           NaN            NaN
6316  NaN           NaN           NaN            NaN
6317  NaN           NaN           NaN            NaN
6318  NaN           NaN           NaN            NaN
6319  NaN           NaN           NaN            NaN
6320  NaN           NaN           NaN            NaN
6321  NaN           NaN           NaN            NaN
6322  NaN           NaN           NaN            NaN
6323  NaN           NaN           NaN            NaN
6324  NaN           NaN           NaN            NaN
6325  NaN           NaN           NaN            NaN
6326  NaN           NaN           NaN            NaN
6327  NaN           NaN           NaN            NaN
6328  NaN           NaN           NaN            NaN
6329  NaN           NaN           NaN            NaN
6330  NaN           NaN           NaN            NaN
6331  NaN           NaN           NaN            NaN
...   ...           ...           ...            ...
8672  NaN           NaN           NaN            NaN
8673  NaN           NaN           NaN            NaN
8674  NaN           NaN           NaN            NaN
8675  NaN           NaN           NaN            NaN
8676  NaN           NaN           NaN            NaN
8677  NaN           NaN           NaN            NaN
8678  NaN           NaN           NaN            NaN
8679  NaN           NaN           NaN            NaN
8680  NaN           NaN           NaN            NaN
8681  NaN           NaN           NaN            NaN
8682  NaN           NaN           NaN            NaN
8683  NaN           NaN           NaN            NaN
8684  NaN           NaN           NaN            NaN
8685  NaN           NaN           NaN            NaN
8686  NaN           NaN           NaN            NaN
8687  NaN           NaN           NaN            NaN
8688  NaN           NaN           NaN            NaN
8689  NaN           NaN           NaN            NaN
8690  NaN           NaN           NaN            NaN
8691  NaN           NaN           NaN            NaN
8692  NaN           NaN           NaN            NaN
8693  NaN           NaN           NaN            NaN
8694  NaN           NaN           NaN            NaN
8695  NaN           NaN           NaN            NaN
8696  NaN           NaN           NaN            NaN
8697  NaN           NaN           NaN            NaN
8698  NaN           NaN           NaN            NaN
8699  NaN           NaN           NaN            NaN
8700  NaN           NaN           NaN            NaN
8701  NaN           NaN           NaN            NaN

[2400 rows x 22 columns]

6297

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,...,N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,...,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,...,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,N,14h00,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,...,N,NaN,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.21,2018.05.21,6292.0
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,...,N,15h00,NaN,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.b,2018.05.13.b,6291.0
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,N,NaN,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0
15,2018.05.12,12-May-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,male,M,...,N,11h00,NaN,"B.Jacob, Dispatch Live, 5/12/2018",2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.12,2018.05.12,6288.0
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,male,M,...,N,10h30,Shark involvement not confirmed,"B. Myatt, GSAF",2018.05.09-SharpesBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.09,2018.05.09,6287.0
17,2018.04.30.R,Reported 30-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,female,M,...,N,NaN,NaN,"K. McMurray, TrackingSharks.com",2018.04.30.R-Thailand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.30.R,2018.04.30.R,6286.0
18,2018.04.28.b,28-Apr-2018,2018.0,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,male,M,...,N,10h40,Tiger shark,Costa Rica Star. 4/28/2018,2018.04.28.b-CostaRica.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.28.b,2018.04.28.b,6285.0
19,2018.04.28.a,28-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,Gearys Beach,Surfing,Adam Murray,M,...,N,16h50,NaN,"B. Myatt, GSAF",2018.04.28.a-Murray.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.28.a,2018.04.28.a,6284.0
20,2018.04.25.b,25-Apr-2018,2018.0,Questionable,AUSTRALIA,New South Wales,Lennox Head,Surfing,Matthew Lee,M,...,N,07h00,Questionable,"B. Myatt, GSAF",2018.04.25.b-Lee.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.25.b,2018.04.25.b,6283.0
21,2018.04.25.a,25-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,...,N,09h30,3 m shark,"B.Myatt, GSAF",2018.04.25.a-Bruce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.25.a,2018.04.25.a,6282.0
22,2018.04.24,24-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"South Point, Gracetown",Surfing,Nathan Burch,M,...,N,Afternoon,"White shark, 3.5 m","B. Myatt, GSAF",2018.04.24-Burch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.24,2018.04.24,6281.0
23,2018.04.23,23-Apr-2018,2018.0,Unprovoked,MALDIVES,Alifu Alifu Atoll,Madoogali,Fishing,Ahmed Rasheed,M,...,N,21h50,Tiger shark,"K. McMurray, TrackingSharks.com",2018.04.23-Maldives.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.23,2018.04.23,6280.0
24,2018.04.22,22-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Western Cape Province,"Robberg Beach, Plettenberg Bay",Paddle-skiing,male,M,...,N,09h40,"White shark, 2.5 m","Africa News Agency, 4/22/2018",2018.04.22-PlettenbergBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.22,2018.04.22,6279.0
25,2018.04.19,19-Apr-2018,2018.0,Unprovoked,USA,Hawaii,"Shipwrecks Beach, Keoneloa Bay, Kauai",Body boarding,Dylan McWilliams,M,...,N,NaN,6' shark,"The Garden Island, 4/19/2018",2018.04.19-McWilliams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.19,2018.04.19,6278.0
26,2018.04.15.d,15-Apr-2018,2018.0,Unprovoked,THAILAND,Hua Hin,Sai Noi Beach,Swimming,Werner Danielsen,M,...,N,NaN,Juvenile bull shark,"Straits Times, 4/16/2018",2018.04.15.d-Thailand.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.d,2018.04.15.d,6277.0
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,...,NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0
28,2018.04.15.b,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Lefthanders, Margaret River Area",Surfing,Jason Longrass,M,...,N,NaN,NaN,"B.Myatt, GSAF",2018.04.15.b-Longrass.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.b,2018.04.15.b,6275.0
29,2018.04.15.a,15-Apr-2018,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Cobblestones, Margaret River Area",Surfing,Alejandro Travaglini,M,...,N,08h00,NaN,"B.Myatt, GSAF",2018.04.15.a-Travaglini.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.a,2018.04.15.a,6274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6271,ND.0032,World War II,0.0,Sea Disaster,PAPUA NEW GUINEA,Between New Ireland & New Britain,St. Georges Channel,Spent 8 days in dinghy,pilot,M,...,N,NaN,NaN,"G.A. Llano in Airmen Against the Sea, p.69; V....",ND-0032-RabaulPilot.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0032,ND.0032,32.0
6272,ND.0031,World War II,0.0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,...,N,NaN,NaN,"V.M. Coppleson (1962), p.257",ND-0031-Ditched-Aircrat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0031,ND.0031,31.0
6273,ND.0030,Before 1905,0.0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,...,Y,NaN,NaN,"Massillon Independent, 3/1905",ND-0030-Burma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0030,ND.0030,30.0
6274,ND.0028,A few years before 1938,0.0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,...,N,NaN,White shark,A. De Maddalena; Anon. (1938),ND-0028-Maciotta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0028,ND.0028,29.0
6275,ND.0027,No date,0.0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,...,N,NaN,NaN,M. N. Kalafatas,ND-0027-Psarofagomenos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0027,ND.0027,28.0
6276,ND.0026,Early 1930s,0.0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,...,Y,NaN,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27.0
6277,ND.0025,Before 1927,0.0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,...,UNKNOWN,NaN,NaN,H. Capper,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0025,ND.0025,26.0
6278,ND.0024,Between 1918 & 1939,0.0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,...,Y,NaN,NaN,G. Van Grevelynghe,ND-0024-Barachois-Reunion.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0024,ND.0024,25.0
6279,ND.0023,No date,0.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,Wading,Madelaine Dalton,F,...,N,NaN,NaN,"L. Green in Tavern of the Seas, p.182",ND-0023-Dalton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0023,ND.0023,24.0
6280,ND.0022,No date,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Pearl diving,Jaringoorli,M,...,N,NaN,NaN,"Adelaide Advertiser, 1/11/1940",ND-0022-Jaringoorli.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0022,ND.0022,23.0
6281,ND.0021,No date,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Swimming in pool formed by construction of a w...,Indian boy,M,...,Y,NaN,NaN,"L. Green in South African Beachcomber, p.97",ND-0021-DurbanIndianBoy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0021,ND.0021,22.0
6282,ND.0020,1920 -1923,0.0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,...,Y,NaN,NaN,"V.M. Coppleson (1958), p.241",ND-0020-3JapaneseDivers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0020,ND.0020,21.0
6283,ND.0019,Before 1921,0.0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,...,N,NaN,NaN,"T. Helm, p.219",ND-0019-Kelley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0019,ND.0019,20.0
6284,ND.0018,Before 1911,0.0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng Tàu,Swimming around anchored ship,crewman,M,...,N,NaN,NaN,"Daily Kennebec Journal, 3/27/1911",ND-0018-Vietnam.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0018,ND.0018,19.0
6285,ND.0017,Before 1921,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,Y,NaN,NaN,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0017-alongside-ship.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0017,ND.0017,18.0
6286,ND.0016,Before 1921,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,Y,NaN,NaN,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0016- Durban-PostOffice.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0016,ND.0016,17.0
6287,ND.0015,Before 1917,0.0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,...,Y,NaN,NaN,"Fijian Society papers presented April 17, 1918...",ND-0015-FijianCanoe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0015,ND.0015,16.0
6288,ND.0014,Before 17-Jul-1916,0.0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,...,N,NaN,NaN,"C. Creswell, GSAF; Wilmington Star, 7/17/1916",ND-0014-pre1916-NorthCarolina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0014,ND.0014,15.0
6289,ND.0013,No date (3 days after preceding incident) & pr...,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,a native fisherman,M,...,Y,NaN,NaN,"Rural New Yorker, 7/19/1913",ND-0013-Durban-native-fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0013,ND.0013,14.0
6290,ND.0012,Before 19-Jul-1913,0.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,a young Scotsman,M,...,Y,NaN,NaN,"Rural New Yorker, 7/19/1913",ND-0012-Durban-Scotsman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0012,ND.0012,13.0
6291,ND.0011,Before 1911,0.0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,...,N,NaN,NaN,"Ref. J. T. Dubois in N.Y. Sun, 3/19/1911",ND-0011-Masury.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0011,ND.0011,12.0
6292,ND.0010,Circa 1862,0.0,Unprovoked,USA,Hawaii,Puna,NaN,"A ""chiefess""",F,...,N,NaN,NaN,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11.0
6293,ND.0009,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0009,ND.0009,10.0
6294,ND.0008,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Y,NaN,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9.0
6295,ND.0007,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Y,NaN,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8.0
6296,ND.0006,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,Y,NaN,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0006,ND.0006,7.0
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0

### 1.2 find the rows and columns whose contents are duplicate

In [5]:
import numpy as np
#rows
df = df.drop_duplicates()
print(len(df))

#columns
df.shape[1]
df['Case Number'] = np.where((df['Case Number'] == df['Case Number.1']) & (df['Case Number'] == df['Case Number.2'])
                     , df['Case Number'], df['Case Number'])
df = df.drop(['Case Number.1','Case Number.2'], axis=1)
df.head()

6297

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0

In [6]:
display(df[ df['Case Number'].isnull() == True])
df = df.dropna(how='any')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,original order
5488,NaN,Reported 06-Sep-1905,1905.0,Provoked,USA,Florida,"Fort Pierce, St Lucie County",Fishing,David Curry,M,NaN,Lacerations to leg from hooked shark PROVOKED ...,N,NaN,NaN,"Muncie Evening Press, 8/6/1913",1905.09.06.R-Curry.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,815.0

### 1.3 dropping unnecessary columns

In [7]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'original order'],
      dtype='object')

In [8]:
df = df.drop(['Name', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'original order'],axis=1)
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'"
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident

## 2. renaming columns and skipping rows

### Date

In [9]:
# extracting months from "date" column

# months:
df['Date'] = df["Date"].replace('Jan','01',regex =True)
df['Date'] = df["Date"].replace('Feb','02',regex =True)
df['Date'] = df["Date"].replace('Mar','03',regex =True)
df['Date'] = df["Date"].replace('Apr','04',regex =True)
df['Date'] = df["Date"].replace('May','05',regex =True)
df['Date'] = df["Date"].replace('May','05',regex =True)
df['Date'] = df["Date"].replace('Jun','06',regex =True)
df['Date'] = df["Date"].replace('Jul','07',regex =True)
df['Date'] = df["Date"].replace('Aug','08',regex =True)
df['Date'] = df["Date"].replace('Sep','09',regex =True)
df['Date'] = df["Date"].replace('Oct','10',regex =True)
df['Date'] = df["Date"].replace('Nov','11',regex =True)
df['Date'] = df["Date"].replace('Dec','12',regex =True)
# removing non numeric characters and any whitespace character:
df['Date'] = df["Date"].replace('[a-zA-Z]','',regex =True)
df['Date'] = df["Date"].replace('\s','',regex =True)
# r years:
df['Date'] = df["Date"].replace('\d\d\d\d','',regex =True)
# r days:
df['Date'] = df["Date"].replace('^\d+-','',regex =True)
# r points , 0 , -
df['Date'] = df["Date"].replace('\.','',regex =True)
df['Date'] = df["Date"].replace('\-','',regex =True)
df['Date'] = df["Date"].replace('^\d{3,}','',regex =True)
df['Date'] = df["Date"].replace('0','',regex =True)
df['Date'] = df["Date"].replace('','1',regex =True)


df['Date'].unique()
df['Date'].value_counts()

1     281
9     145
8     140
7     129
6     125
4     115
12    100
5     100
3      98
11     97
2      89
93      1
15      1
22      1
Name: Date, dtype: int64

In [10]:
#r values != 1-12
def getMonth(*month):
    if month[0]=="":
        return 0
    elif int(month[0])>12:
        return 0
    return int(month[0])

df['Date']= df['Date'].apply(getMonth)


#removing rows if value = 0
df = df.drop(df[df['Date'] == 0].index, axis=0)
df['Date'].unique()

#renaming column
df = df.rename(columns={'Date': 'MONTH'})
df.head()

,Case Number,MONTH,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2018.06.25,6,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark
8,2018.05.26.b,5,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'"
10,2018.05.24,5,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark
13,2018.05.13.a,5,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident


#### A: MONTH
### Year

In [11]:
df.sort_values(by=['Year'], axis=0, ascending=True)


df['Year'].value_counts()

# 2018.0 > return int
def returnInt(*n):
    return int(n[0])
df['Year'] = df['Year'].apply(returnInt)


df = df.rename(columns={'Year':'YEAR'})
df.head()

,Case Number,MONTH,YEAR,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Time,Species
0,2018.06.25,6,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark
6,2018.06.03.a,6,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,18,FATAL,Y,Late afternoon,Tiger shark
8,2018.05.26.b,5,2018,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'"
10,2018.05.24,5,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark
13,2018.05.13.a,5,2018,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident

#print(df['YEAR'].describe())
#print(df['YEAR'][1000:2000].value_counts())


#df["New"] = df['YEAR'].apply(lambda x: x if df['YEAR'].value_counts().sum() < 10)

nvalues = df['YEAR'].value_counts()

def removeLessThanXValues(*row):
    if nvalues[0].sum() < 15:
        return 'OTHER COUNTRIES'
    return row[0]

df['YEAR'] = df['YEAR'].apply(removeLessThanXValues)

In [12]:
df = df.drop(df[df['YEAR']<1950].index, axis=0)
df['YEAR'].value_counts()

2015    62
2012    54
2002    53
2007    52
2013    49
2005    41
2003    40
2004    39
2009    39
2006    38
2010    36
2016    35
2008    34
2011    33
2014    33
2000    33
2001    29
1999    25
1961    25
2017    25
1995    23
1963    23
1998    22
1992    22
1962    22
1997    19
1993    19
1996    19
1966    17
1959    17
        ..
1983    13
1990    13
1964    13
1975    12
1974    11
1984    11
1987    11
1982    11
1980    10
1967    10
1985    10
1971     9
1968     8
1976     8
1965     8
1957     7
1972     6
1950     6
1977     5
1969     5
1956     5
1955     5
1951     5
1979     4
1978     3
1954     3
1973     3
1970     2
1953     2
1952     2
Name: YEAR, Length: 69, dtype: int64

#### A: MONTH, YEAR
### TYPE

In [13]:
df['Type'] = df['Type'].replace('Boating','Unprovoked',regex =True)
df['Type'] = df['Type'].replace('Sea Disaster','Unprovoked',regex =True)
df = df.drop(df[(df['Type'] != 'Unprovoked') & (df['Type'] != 'Provoked') ].index, axis = 0)

df['Type'].value_counts()

Unprovoked    1230
Provoked        99
Name: Type, dtype: int64

In [14]:
df = df.rename(columns={'Type':'TYPE'})
df['TYPE'].value_counts()

Unprovoked    1230
Provoked        99
Name: TYPE, dtype: int64

#### A: MONTH, YEAR, TYPE
### COUNTRY

In [15]:
df = df.rename(columns={'Country':'COUNTRY'})
df['COUNTRY'].value_counts()

USA                               665
AUSTRALIA                         256
SOUTH AFRICA                      198
BAHAMAS                            23
NEW ZEALAND                        20
REUNION                            15
BRAZIL                             14
PAPUA NEW GUINEA                   12
MEXICO                             11
NEW CALEDONIA                      10
EGYPT                               9
FRENCH POLYNESIA                    8
MOZAMBIQUE                          7
FIJI                                7
ITALY                               6
TONGA                               3
VIETNAM                             3
INDONESIA                           3
CUBA                                3
CROATIA                             3
SPAIN                               3
TAIWAN                              3
JAPAN                               3
NEW BRITAIN                         2
AMERICAN SAMOA                      2
ECUADOR                             2
PALAU                               2
VENEZUELA                           2
VANUATU                             2
HONG KONG                           2
MARSHALL ISLANDS                    2
JAMAICA                             1
COSTA RICA                          1
THAILAND                            1
MALDIVES                            1
RUSSIA                              1
SENEGAL                             1
PACIFIC OCEAN                       1
FEDERATED STATES OF MICRONESIA      1
ISRAEL                              1
GRAND CAYMAN                        1
SCOTLAND                            1
GREECE                              1
SOUTH KOREA                         1
SEYCHELLES                          1
COLUMBIA                            1
OKINAWA                             1
NORTH PACIFIC OCEAN                 1
ST. MAARTIN                         1
BRITISH WEST INDIES                 1
EL SALVADOR                         1
SOLOMON ISLANDS                     1
ENGLAND                             1
GUAM                                1
UNITED KINGDOM                      1
MICRONESIA                          1
ARGENTINA                           1
TURKS & CAICOS                      1
BERMUDA                             1
Name: COUNTRY, dtype: int64

#### A: MONTH, YEAR, TYPE, COUNTRY
### SEX

In [16]:
df['Sex '] = df['Sex '].str.replace(" M ","M")
df['Sex '] = df['Sex '].str.replace("N ","M")
df = df.drop(df[df['Sex '] == ' .' ].index,axis=0)
df = df.drop(df[df['Sex '] == ' lli ' ].index,axis=0)

df = df.rename(columns={'Sex ':'SEX'})
df['SEX'].value_counts()

M      1139
F       189
lli       1
Name: SEX, dtype: int64

#### A: MONTH, YEAR, TYPE, COUNTRY, SEX
### AGE

Children (0-14)

Youth (15-24 years)

Young Adults (25-40 years)

Adults (41-64 years)

Seniors (65 years and over)

In [17]:
df.head()
df.columns

Index(['Case Number', 'MONTH', 'YEAR', 'TYPE', 'COUNTRY', 'Area', 'Location',
       'Activity', 'SEX', 'Age', 'Injury', 'Fatal (Y/N)', 'Time', 'Species '],
      dtype='object')

In [18]:
df['Age'] = df['Age'].replace('\D','0',regex =True)
df['Age'] = df['Age'].replace('\s','0',regex =True)
df['Age'] = df['Age'].replace('^\d{3,}','0',regex =True)

df['Age'].unique()

array(['57', '18', '15', '32', '30', '60', '33', '19', '25', '10', '69',
       '55', '35', '20', '54', '22', '31', '40', '37', '13', '34', '50',
       '46', '48', '17', '28', '65', '73', '58', '36', '0', '51', '21',
       '61', '59', '42', '6', '23', '29', '39', '24', '12', '26', '11',
       '71', '43', '44', '14', '27', '62', '52', '38', '68', '16', '47',
       '63', '70', '9', '41', '53', '7', '66', '45', '74', '64', '8',
       '56', '49', '77', '84', '00', '5'], dtype=object)

In [19]:
display(df[ df['Age'].isnull() == True])
df.shape

Empty DataFrame
Columns: [Case Number, MONTH, YEAR, TYPE, COUNTRY, Area, Location, Activity, SEX, Age, Injury, Fatal (Y/N), Time, Species ]
Index: []

(1329, 14)

In [20]:
def ChangeYears(years):
    if int(years) >= 0 and int(years) <= 14: return "Children"
    elif int(years) > 14 and int(years) <= 24: return "Youth"
    elif int(years) > 24 and int(years) <= 35: return "Young Adult"
    elif int(years) > 35 and int(years) <= 64: return "Adult"
    elif int(years) > 64 and int(years) <= 99: return "Senior"
    else: return "Null"
    
df['Age'] = df['Age'].apply(ChangeYears)
df['Age'].value_counts()

df = df.rename(columns={"Age":"AGE"})
df.head()

,Case Number,MONTH,YEAR,TYPE,COUNTRY,Area,Location,Activity,SEX,AGE,Injury,Fatal (Y/N),Time,Species
0,2018.06.25,6,2018,Unprovoked,USA,California,"Oceanside, San Diego County",Paddling,F,Adult,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark
6,2018.06.03.a,6,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,Youth,FATAL,Y,Late afternoon,Tiger shark
8,2018.05.26.b,5,2018,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,Youth,Lower left leg bitten,N,17h00,"Bull shark, 6'"
10,2018.05.24,5,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,Young Adult,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark
18,2018.04.28.b,4,2018,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,M,Young Adult,"No injury, shark bit scuba gear",N,10h40,Tiger shark

#### A: MONTH, YEAR, TYPE, COUNTRY, SEX, AGE
### FATAL

In [21]:
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace("n","N")
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace("y","Y")
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace(" N","N")
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace("N ","N")
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace("M","N")
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace("UNKNOWN","NS")
df = df.drop(df[df['Fatal (Y/N)']=="2017"].index,axis=0)

df['Fatal (Y/N)'].value_counts()

N    1146
Y     182
Name: Fatal (Y/N), dtype: int64

In [22]:
print('NULLS:', df['Fatal (Y/N)'].isnull().sum())
df.columns

NULLS: 0

Index(['Case Number', 'MONTH', 'YEAR', 'TYPE', 'COUNTRY', 'Area', 'Location',
       'Activity', 'SEX', 'AGE', 'Injury', 'Fatal (Y/N)', 'Time', 'Species '],
      dtype='object')

In [23]:
df = df.rename(columns={'Fatal (Y/N)':'FATAL'})

#### A: MONTH, YEAR, TYPE, COUNTRY, SEX, AGE, FATAL
### INJURY

http://erd.dli.mt.gov/work-comp-claims/definitions-for-part-of-body

In [24]:
# ----------------------------    UNFINISHED     -------------------------


df['Injury'].value_counts()

#cómo para que sea siempre la primera que encuentre?
def InjuryClassify(injury):
    if 'no injury' in str(injury).lower(): return 'NO INJURY, SLIGHT SCARE!'
    if 'foot' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'feet' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'hip' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'hips' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'leg' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'toe' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'toes' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'knee' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'knees' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'ankle' in str(injury).lower(): return 'LOWER EXTREMITIES'
    if 'ankles' in str(injury).lower(): return 'LOWER EXTREMITIES'
    
    if 'fatal' in str(injury).lower(): return 'FATAL'
    else: return "OTHERS"

    
df['Injury'] = df['Injury'].apply(InjuryClassify)
df = df.rename(columns={'Injury':'INJURY'})
df['INJURY'].value_counts()

LOWER EXTREMITIES           576
OTHERS                      481
FATAL                       136
NO INJURY, SLIGHT SCARE!    135
Name: INJURY, dtype: int64

#### A: MONTH, YEAR, TYPE, COUNTRY, SEX, AGE, FATAL
### SPECIES

In [25]:
df.columns

Index(['Case Number', 'MONTH', 'YEAR', 'TYPE', 'COUNTRY', 'Area', 'Location',
       'Activity', 'SEX', 'AGE', 'INJURY', 'FATAL', 'Time', 'Species '],
      dtype='object')

In [26]:
# ----------------------------    UNFINISHED     -------------------------

df['Species '].value_counts()

def getSpecies(species):
    if "white" in str(species).lower() : return "White shark"
    if "4' shark" in str(species).lower() : return "White shark"
    if "tiger" in str(species).lower() : return "Tiger shark"
    if "bull" in str(species).lower() : return "Bull shark"
    if "raggedtooth" in str(species).lower() : return "Raggedtooth shark"
    else: return "Non defined"

df = df.rename(columns={'Species ':'SPECIES'})
df['SPECIES'] = df['SPECIES'].apply(getSpecies)

df['SPECIES'].value_counts()

Non defined          655
White shark          407
Tiger shark          144
Bull shark            98
Raggedtooth shark     24
Name: SPECIES, dtype: int64

In [27]:
df.head()

,Case Number,MONTH,YEAR,TYPE,COUNTRY,Area,Location,Activity,SEX,AGE,INJURY,FATAL,Time,SPECIES
0,2018.06.25,6,2018,Unprovoked,USA,California,"Oceanside, San Diego County",Paddling,F,Adult,"NO INJURY, SLIGHT SCARE!",N,18h00,White shark
6,2018.06.03.a,6,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,Youth,FATAL,Y,Late afternoon,Tiger shark
8,2018.05.26.b,5,2018,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,Youth,LOWER EXTREMITIES,N,17h00,Bull shark
10,2018.05.24,5,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,M,Young Adult,OTHERS,N,Morning,Non defined
18,2018.04.28.b,4,2018,Unprovoked,COSTA RICA,Cocos Island,Manuelita,Scuba diving,M,Young Adult,"NO INJURY, SLIGHT SCARE!",N,10h40,Tiger shark

#### A: MONTH, YEAR, TYPE, COUNTRY, SEX, AGE, FATAL, SPECIES
### ACTIVITIES

In [28]:
df['Activity'].unique()

array(['Paddling', 'Swimming', 'Walking', 'Feeding sharks',
       'Scuba diving', 'Surfing', 'Fishing', 'Paddle-skiing',
       'Stand-Up Paddleboarding', 'Wading', 'Spearfishing',
       'Night bathing', 'Kayaking / Fishing', 'Snorkeling', 'SUP',
       'Kayaking', 'Body boarding', 'Scuba Diving', 'Surf skiing ',
       'Surf fishing', 'Floating', 'SUP Foil boarding', 'Kite surfing',
       'Floating in tube', 'Standing', 'Diving', 'Teasing a shark',
       'Paddle boarding', 'Kayak Fishing', 'Surf-skiing',
       'Scallop diving on hookah', 'Body boarding ',
       'Playing in the water', 'Body Boarding', 'Boogie boarding',
       'Playing', 'Standing / Snorkeling', 'Hand feeding sharks',
       'Rowing', 'Shark fishing', 'Fishing ', 'Kayaking ', 'Body surfing',
       'Kitesurfing', 'Kiteboarding', 'Diving ', 'Swimming / snorkeling',
       'Diving for Abalone', 'Casting a net', 'Cleaning fish',
       'Boogie Boarding', 'Playing in the surf', 'Kite boarding',
       "Fishing - 'tag & release'", 'Bodyboarding',
       'Swimming or boogie boarding', 'Free diving ',
       'Sitting in the water', 'Free diving / spearfishing',
       'Diving, feeding sharks', 'Kite Surfing', 'Swimming or Snorkeling',
       'Kite Boarding', 'Washing sand off a speared fish', 'Surfing ',
       'Wakeboarding', 'Diving for abalone', 'Rescuing',
       'Measuring sharks', 'Swimming / treading water', 'Wade Fishing',
       'Diving, but on the surface when bitten by the shark',
       'Treading water', 'Walking out of the water after surfing',
       'Jet skiing',
       "Accidentally stood on hooked shark's tail before attempting to gut it ",
       'Jumping', 'Floating near boat & observing bioluminesce',
       'Jumped into the water', 'Reviving a sedated shark',
       'Swimming / jumping off a jetty', 'Spearfishing (free diving)',
       'Swimming / Body Surfing', 'Playing soccer in the water',
       'Lifesaving drill', 'Fishing for sharks', 'Standing / Surfing',
       'Holding onto an inflatable boat', 'Swimming with boogie board',
       'Spearfishing (Free diving)', 'Diving in aquarium display tank',
       'Fishing from a kayak',
       'Scurfing (surfboard being  towed behind a boat)',
       'Chumming for white sharks', 'Bathing',
       'Wading / fishing & carrying a bag of fish',
       'Swimming, poaching perlemoen', 'Free diving & spearfishing',
       'Tandem surfing', 'Wading near a fishing net',
       'Standing, stepped on shark',
       'Swimming, wearing black wetsuit & swim fins',
       'Sitting on surfboard',
       'Walking, carrying surfboard & stepped on shark',
       'Swimming with pod of dolphins', 'Swimming (using a float)',
       'Fishing from Surfboard', 'Boogie boarding or Surfing',
       'Surf skiing', 'Wading, when he stepped on the shark',
       'Shark Fishing', 'Snorkeling (filming the sardine run)',
       'Floating on a raft', 'Fishing, removing the shark from his line',
       'Scallop diving (using surface-supplied air & a POD) ',
       'Surfing, but standing in water alongside board',
       'Swimming / Wading', 'Body-boarding',
       'Swimming /  boogie boarding',
       'Surfing, fell off surfboard & stepped on the shark.', 'Swimming ',
       'Standing alongside surfboard',
       'Swimming back from anchored sailboat', 'Swimming / Body surfing',
       'Free diving', 'Windsurfing, but sitting on his board',
       'Surfing / Wading',
       'Spearfishing, holding mesh bag with speared fish',
       'Spearfishing, but swimming at surface',
       'Surfing, lying on surfboard', "Lying prone in 2' of water",
       'Spearfishing & holding catch', 'Swimming with dolphins',
       'Wading in school of baitfish', 'Splashing / wading',
       'Windsurfing',
       'Swimming after being swept into sea by a large wave',
       'Swimming near pod of whales', 'Free diving for abalone',
       'Towing rubber dinghy', 'Surfing (lying prone on his board)',
       'Snorkeling \x96 hunting crayfish and abalone',
       'Swimming or paddle boarding',
       'Scuba diving (submerged riding a scooter)',
       'Body boarding or surfing', 'Surfing (sitting on his board)',
       'Wading / Surfing', 'Body surfing, stood up on sandbar',
       'Surfing / Swimming', 'Wade fishing', 'Swimming breast stoke',
       'Dived naked into the water on a bet',
       'Swimming with mask & snorkel', 'Playing / standing',
       'Abalone diving using Hookah (near calving whales)',
       'Abalone diving using Hookah (resting on the surface)',
       'Scuba diving (ascending using scooter)',
       'Scuba diving for bivalves',
       'Commercial diver (submerged or treading water)',
       'Surfing, paddling seawards', 'Jumped off rocks into white water',
       'Hookah diving', 'Riding floatation device',
       'Free diving for abalone (ascending)',
       'Paddling on surfboard or body board',
       'Scuba diving at seal colony', 'Paddling on surfboard',
       'Free diving & spearfishing (ascending)',
       'Standing in waist-deep water, helping his father tend a gill net containing dead fish',
       'Lying on surfboard', 'Spearfishing / free diving',
       'Scuba diving (submerged)', 'Hookah diving for sea urchins',
       'Hookah diving for pen shells ', 'Finning the shark that bit him',
       'Canoeing', 'Swimming behind sailboat',
       'Surfing, collided with shark',
       'Free diving / spearfishing, from paddleboard & floating on the surface',
       'Scuba diving (but on surface)', 'Resting on surfboard',
       'Lying on surfboard & paddling',
       "Fishing, stepped on hooked shark's head",
       'Hookah diving for abalone (descending)', 'Feeding fish',
       'Scuba diving, but swimming on surface', 'Surfing with dolphins',
       'Sittting in water with his child', 'Lying atop surfboard',
       "Attempting to lasso shark's tail",
       'Free diving  & spearfishing (submerged)', 'Racing ski',
       'Hookah diving for abalone', 'Free diving for scallops',
       'Scuba Diving for lobster (at surface)',
       'Sailing on catamaran & fell into the water',
       'Surfing or body surfing', 'Skindiving',
       'Towing her sister on plastic ski board',
       'Swimming from the New Venture ',
       '14 m prawn trawler New Venture capsized  & sank in heavy seas Three people in the water',
       'Water-skiing', 'Paddleskiing',
       'Free diving for abalone from Zodiac (submerged)',
       'Paddle Boarding', 'Snorkeling on surface', 'Shell diving',
       'Standing / Wading', 'Free diving for abalone (surfacing)',
       'Spearfishing / Scuba diving',
       'Hookah diving for abalone (submerged)',
       'Thrashing the water / imitating the shark victim from "Jaws"',
       'Scuba diving & spearfishing', 'Floating on a small orange raft ',
       'Scuba diving for abalone',
       'Scuba diving for abalone (at surface)',
       'Swimming underwater from crayfish cage to a fishing bait',
       'Free diving (but on surface)', 'Free diving, Spearfishing',
       'Sitting in shallows', 'Scuba diving & feeding fish',
       'Feeding mullet to sharks', 'Dynamite fishing',
       'Spearfishing using Scuba',
       'Wading & pushing dinghy toward  the shallows',
       'Standing on sandbar', 'Pulling shark from the water',
       'Spearfishing, dived to pick up a float line',
       'Photographing sharks underwater using Scuba',
       'Free diving, carrying speargun', 'Diving into water',
       'Killing a shark', 'Clamming', 'Helping men land a shark',
       'Free diving / spearfishing (resting on the surface)',
       'Walking on reef', 'Paddling rescue ski',
       'Canoe swamped, swimming back to canoe', 'Free diving with seals',
       'Surfing, but swimming to his board',
       'Floating on his back in an inner tube',
       'Spearfishing using scuba', 'Skin diving ',
       'Spearfishing / Scuba diving (at surface)',
       'Helping friend land hooked shark', 'Splashing in surf',
       'Treading water while alongside capsized yacht',
       'Fishing / standing in waist deep water', 'Surf fishing, wading ',
       'Spearing fish', 'Spearfishing, pulled shark\x92s tail',
       'Free diving, hunting crayfish', 'Spearfishing with Scuba gear',
       'Surf fishing in waist-deep water', 'Fishing for albacore',
       'Rolled off raft',
       'Scuba diving, attempting to catch a captive shark', 'Splashing ',
       "Fishing with hand net in 2' of water",
       'Surfing, pushing board ashore',
       'Swimming with other crew near wharf',
       'Net fishing, picking catch from the net',
       'Walking in chest-deep water',
       'Checking fish traps, fell into the water',
       'Swimming, using bundles of sticks as raft',
       'Spearfishing, shark grabbed his white t-shirt and towed him ',
       'Collecting aquarium specimens',
       'Fishing, when line became snagged on rock & he dived into water to free it ',
       'Holding shark on leader & dangling it above the water',
       'Fishing, tossing netted shark onboard',
       'Free diving but treading water at surface',
       'Skindiving for abalone (but at surface)',
       'Wading, fishing for flounder', 'Standing in chest-deep water',
       'Trailing the field in a surf race',
       "Swimming at surface through school of feeding 2.5' to 5\x92 sharks",
       "Adrift, hanging onto cushion, after his 17' skiff ran out of gas & capsized 3 miles from shore",
       'Spearfishing (but on surface)', 'Working prawn net',
       'In deep water about 100 yards from his ship',
       'Surfing, but treading water', 'Surfing on air mattress',
       'Cleaning hull of ship ',
       'Swimming, ducking for shells in water 0.9 m deep',
       'U.S. Airforce C124 enroute from Hickham Air Base to Japan went down. The 3 survivors fashioned raft from mailbags  & were rescued 3 days after the crash.',
       'Spearfishing, had fish on his spear',
       'Paddling in knee-deep water', 'Swimming with goggles',
       'Competing in spearfishing championship & towing dead fish',
       'Swimming between  anchored  pearling luggers',
       'Skindiving, fish at belt', 'Swimming near pier',
       'Swimming, attacked at  surf carnival',
       'Hunting lobsters in 2.4 m of water',
       'Pearl diving from lugger Whyalla', 'Crouching in the water',
       'Fishing, setting nets', 'Body surfing & treading water',
       'Fell off surf ski', 'Body surfing / treading water',
       'Jerked overboard while pole fishing for tuna', 'Bending over'],
      dtype=object)

In [29]:
from collections import Counter
words = [str(elem).lower() for elem in df['Activity']]
words = ' '.join(words).split()
Counter(words).most_common(30)

[('surfing', 447),
 ('swimming', 211),
 ('spearfishing', 121),
 ('diving', 112),
 ('boarding', 66),
 ('fishing', 64),
 ('body', 62),
 ('wading', 55),
 ('water', 49),
 ('on', 47),
 ('scuba', 46),
 ('snorkeling', 42),
 ('standing', 40),
 ('for', 36),
 ('free', 36),
 ('the', 34),
 ('/', 30),
 ('in', 30),
 ('abalone', 26),
 ('&', 26),
 ('a', 23),
 ('shark', 21),
 ('boogie', 19),
 ('treading', 19),
 ('surf', 17),
 ('from', 17),
 ('kayaking', 16),
 ('his', 16),
 ('with', 14),
 ('surfboard', 14)]

In [30]:
display(df['Activity'])

0                                           Paddling
6                                           Swimming
8                                            Walking
10                                    Feeding sharks
18                                      Scuba diving
21                                           Surfing
23                                           Fishing
24                                     Paddle-skiing
34                                           Surfing
35                           Stand-Up Paddleboarding
36                                            Wading
37                                          Swimming
38                                           Surfing
40                                          Swimming
42                                           Walking
51                                           Surfing
53                                           Surfing
60                                      Spearfishing
63                                           Surfing
64                                     Night bathing
66                                           Surfing
71                                Kayaking / Fishing
74                                           Surfing
75                                        Snorkeling
87                                           Surfing
89                                           Surfing
96                                           Surfing
100                                              SUP
102                                         Swimming
104                                          Fishing
                            ...
4202                                        Standing
4203    Swimming between  anchored  pearling luggers
4222                                    Spearfishing
4228                        Skindiving, fish at belt
4238                              Swimming near pier
4258            Swimming, attacked at  surf carnival
4260                               Diving into water
4275                                        Swimming
4286                                        Swimming
4303                                    Spearfishing
4304                                        Swimming
4308              Hunting lobsters in 2.4 m of water
4340                Pearl diving from lugger Whyalla
4349                                        Floating
4350                          Crouching in the water
4370                                    Spearfishing
4387                                    Spearfishing
4395                           Fishing, setting nets
4399                   Body surfing & treading water
4426                                  Treading water
4427                                        Swimming
4429                                  Treading water
4446                               Fell off surf ski
4449                                    Body surfing
4459                                    Body surfing
4461                   Body surfing / treading water
4462                                         Fishing
4463    Jerked overboard while pole fishing for tuna
4482                                    Body surfing
4489                                    Bending over
Name: Activity, Length: 1328, dtype: object

def getVerbs (words):
    lista = []
    for w in words:
        if 'ing' in w:
            lista.append(w)
    else:
        pass
    return lista

def getVerbs_regex (sentence):
    regex = '\w*ing'
    if re.search(regex, str(sentence)):
        sentence = sentence.replace(str(sentence), regex)
        return sentence
    else: return 'OTHERS'

def getVerbs (words): 
    lista = [] 
    if 'ing' in words:
        lista.append('\w*ing', regex=True) 
    else:
        lista.append('OTHERS')  
    return lista
df['Activity'] = df['Activity'].apply(getVerbs)
display(df['Activity'])


df['Activity'] = df['Activity'].apply(getVerbs_regex)
df = df.rename(columns={"Activity":'ACTIVITY'})
df['ACTIVITY'].value_counts()




def getVerbs_regex (sentence):
    #sentence = str(sentence)
    print(sentence)
    found = re.findall('\w*ing', sentence)[0]
    #findall devuleve una lista, no una string
    #con [0] me devuelve el primer elemento
    if found != '':
        sentence = sentence.replace(sentence,found)
        return sentence
    else: 
        return 'OTHERS'

In [31]:
# actions
import re

def getVerbs_regex (sentence):
    sentence = str(sentence)
    #print(sentence)
    found = re.search('\w*ing', sentence)
    #print(found)
    #print(found.group(0))
    if found:
        sentence = sentence.replace(sentence,found.group())
        return sentence
    else: 
        return 'Undefined'

df['Activity'] = df['Activity'].apply(getVerbs_regex)
display(df['Activity'])
#a = [getVerbs_regex(a) for a in df['Activity']]
#print(a)
#list index out of range: la longitud de uno no es igual que la longitud del otro

0             Paddling
6             Swimming
8              Walking
10             Feeding
18              diving
21             Surfing
23             Fishing
24              skiing
34             Surfing
35      Paddleboarding
36              Wading
37            Swimming
38             Surfing
40            Swimming
42             Walking
51             Surfing
53             Surfing
60        Spearfishing
63             Surfing
64             bathing
66             Surfing
71            Kayaking
74             Surfing
75          Snorkeling
87             Surfing
89             Surfing
96             Surfing
100          Undefined
102           Swimming
104            Fishing
             ...
4202          Standing
4203          Swimming
4222      Spearfishing
4228        Skindiving
4238          Swimming
4258          Swimming
4260            Diving
4275          Swimming
4286          Swimming
4303      Spearfishing
4304          Swimming
4308           Hunting
4340            diving
4349          Floating
4350         Crouching
4370      Spearfishing
4387      Spearfishing
4395           Fishing
4399           surfing
4426          Treading
4427          Swimming
4429          Treading
4446         Undefined
4449           surfing
4459           surfing
4461           surfing
4462           Fishing
4463           fishing
4482           surfing
4489           Bending
Name: Activity, Length: 1328, dtype: object

### En cada uno de estos casos, cuáles son las SEGUNDAS REPETIDAS: buscar estas palabras en la lista de frases anterior y, si aparecen, devolverme esa + la segunda

In [37]:
df.columns

Index(['Case Number', 'MONTH', 'YEAR', 'TYPE', 'COUNTRY', 'Area', 'Location',
       'Activity', 'SEX', 'AGE', 'INJURY', 'FATAL', 'Time', 'SPECIES'],
      dtype='object')

In [38]:
df = df.rename(columns={'Activity':'ACTIVITY'})
df.head()

,Case Number,MONTH,YEAR,TYPE,COUNTRY,Area,Location,ACTIVITY,SEX,AGE,INJURY,FATAL,Time,SPECIES
0,2018.06.25,6,2018,Unprovoked,USA,California,"Oceanside, San Diego County",Paddling,F,Adult,"NO INJURY, SLIGHT SCARE!",N,18h00,White shark
6,2018.06.03.a,6,2018,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,M,Youth,FATAL,Y,Late afternoon,Tiger shark
8,2018.05.26.b,5,2018,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,M,Youth,LOWER EXTREMITIES,N,17h00,Bull shark
10,2018.05.24,5,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding,M,Young Adult,OTHERS,N,Morning,Non defined
18,2018.04.28.b,4,2018,Unprovoked,COSTA RICA,Cocos Island,Manuelita,diving,M,Young Adult,"NO INJURY, SLIGHT SCARE!",N,10h40,Tiger shark

In [39]:
columns_c = ["SEX","AGE","ACTIVITY","COUNTRY","MONTH","YEAR","SPECIES","TYPE","FATAL","INJURY"]
ataques = df[columns_c]
display(ataques.head())
ataques.shape

,SEX,AGE,ACTIVITY,COUNTRY,MONTH,YEAR,SPECIES,TYPE,FATAL,INJURY
0,F,Adult,Paddling,USA,6,2018,White shark,Unprovoked,N,"NO INJURY, SLIGHT SCARE!"
6,M,Youth,Swimming,BRAZIL,6,2018,Tiger shark,Unprovoked,Y,FATAL
8,M,Youth,Walking,USA,5,2018,Bull shark,Unprovoked,N,LOWER EXTREMITIES
10,M,Young Adult,Feeding,AUSTRALIA,5,2018,Non defined,Provoked,N,OTHERS
18,M,Young Adult,diving,COSTA RICA,4,2018,Tiger shark,Unprovoked,N,"NO INJURY, SLIGHT SCARE!"

(1328, 10)

In [41]:
ataques_clean = ataques.to_csv('ataques_clean.csv', header='columns_c')

In [ ]:

--------------------------------------------    WIP    --------------------------------------------  










grouped = ataques.groupby('COUNTRY').count()
display(grouped)
grouped.apply(lambda x : x.groupby('YEAR').count()/x.shape[0]).rename(columns={'On':'Prob'}).reset_index()

In [ ]:


# given two events A and B, the probability of the union A U B is given by the formula 
#P(A U B) = P(A) + P(B) - P( AB) where AB represents the intersection of A and B. 
#Most of us even know that
#P(A U B U C) = P(A) + P(B) + P(C) - { P(AB) + P(AC) + P(BC) } + P(ABC)
    #REFERENCIA:       https://www.datasciencecentral.com/profiles/blogs/a-beautiful-probability-theorem


# ACTIVIDAD, GENERO, LUGAR, MES, AÑO  >   TIBURÓN / MUERTE O NO



# Si hago un data.groupby[de las columnas].count()
# y luego las ordeno, qué ? podré hacer lo de la probabilidad de esta manera?

In [ ]:
# How to plot a heatmap from pandas DataFrame
# https://stackoverflow.com/questions/22923775/calculate-pandas-dataframe-time-difference-between-two-columns-in-hours-and-minu