# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv('../pokemon.csv')
pokemon = df.copy()
pokemon.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [31]:
# HOW TOTAL IS COMPUTED
# Selecciono los set que hacen referencia a habilidades del pokemón y las sumo:
pokemon['Check_Total'] = pokemon.loc[:,"HP":'Speed'].sum(1)
pokemon['Check_Total'].head(10)
#Incluyo el resultado en una nueva columna, y compruebo si los resultados coindicen con los de la columna "Total"
len(pokemon)== (len(pokemon['Check_Total'] == pokemon['Total'])) # yes !
(pokemon['Check_Total'] == pokemon['Total']).head(10) 
# SI COINCIDEN. ESTÁ CALCULADO DE ESA MANERA

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [32]:
# GET_DUMMIES:  CONVERTIR COLUMNAS CATEGÓRICAS EN COLUMNAS NUMÉRICAS

pokemon = pokemon.fillna(0)
Encoded = pd.get_dummies(pokemon["Type 1"]) + pd.get_dummies(pokemon["Type 2"])
Encoded.head()

# De esta manera obtengo el resultado que me dan arriba,
# Pero tengo una columna que ha aparecido llena de valores nulos. por qué??
# He visto que se puede resolver con la función stack -- pendeinte de ver -- dum.stack().str.get_dummies().sum(level=0)

,0,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water
0,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
2,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [33]:
Encoded["Total"] = pokemon["Total"]
Encoded.head()

,0,Bug,Dark,Dragon,Electric,Fairy,Fighting,Fire,Flying,Ghost,Grass,Ground,Ice,Normal,Poison,Psychic,Rock,Steel,Water,Total
0,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,318
1,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,405
2,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,525
3,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,625
4,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,309

In [34]:
# PREGUNTAR Encoded.corr(pokemon['Total']).sort_values(scending = False)

In [35]:
correlation = Encoded.corr()["Total"].sort_values(ascending = False)
display(correlation)

Total       1.000000
Dragon      0.229705
Psychic     0.124688
Steel       0.109703
Fire        0.078726
Fighting    0.077786
Ice         0.060248
Flying      0.059383
Dark        0.056154
Rock        0.032731
Electric    0.020971
Ground      0.015060
Ghost       0.003641
Water      -0.021665
Fairy      -0.036698
Grass      -0.052592
Poison     -0.090441
Normal     -0.105331
Bug        -0.145781
0                NaN
Name: Total, dtype: float64

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [36]:
# UNNFINISHED


#Cuáles son los dos mejores de Type 1 y Type 2 en función del total?
pokemon.sort_values(['Total','Type 1','Type 2'], ascending = False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Check_Total
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,780
164,150,MewtwoMega Mewtwo Y,Psychic,0,780,106,150,70,194,120,140,1,True,780
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,780
422,382,KyogrePrimal Kyogre,Water,0,770,100,150,90,180,160,90,3,True,770
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True,770
552,493,Arceus,Normal,0,720,120,120,120,120,120,120,4,True,720
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False,700
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,700
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False,700
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True,700
420,381,LatiosMega Latios,Dragon,Psychic,700,80,130,100,160,120,110,3,True,700
711,646,KyuremBlack Kyurem,Dragon,Ice,700,125,170,100,120,90,95,5,True,700
712,646,KyuremWhite Kyurem,Dragon,Ice,700,125,120,90,170,100,95,5,True,700
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False,700
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False,700
541,484,Palkia,Water,Dragon,680,90,120,100,150,120,100,4,True,680
540,483,Dialga,Steel,Dragon,680,100,120,120,150,100,90,4,True,680
269,249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True,680
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,680
162,150,Mewtwo,Psychic,0,680,106,110,90,154,90,130,1,True,680
544,487,GiratinaAltered Forme,Ghost,Dragon,680,150,100,120,100,120,90,4,True,680
545,487,GiratinaOrigin Forme,Ghost,Dragon,680,150,120,100,120,100,90,4,True,680
270,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True,680
792,716,Xerneas,Fairy,0,680,126,131,95,131,98,99,6,True,680
425,384,Rayquaza,Dragon,Flying,680,105,150,90,150,90,95,3,True,680
706,643,Reshiram,Dragon,Fire,680,100,120,100,150,120,90,5,True,680
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True,680
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True,680
421,382,Kyogre,Water,0,670,100,100,90,150,140,90,3,True,670
313,289,Slaking,Normal,0,670,150,160,100,95,65,100,3,False,670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,293,Whismur,Normal,0,240,64,51,23,51,23,28,3,False,240
727,659,Bunnelby,Normal,0,237,38,36,38,32,36,57,6,False,237
320,296,Makuhita,Fighting,0,237,72,60,30,20,30,25,3,False,237
316,292,Shedinja,Bug,Ghost,236,1,90,45,30,30,40,3,False,236
457,412,Burmy,Bug,0,224,40,29,45,29,45,36,4,False,224
293,270,Lotad,Water,Grass,220,40,30,30,40,50,30,3,False,220
488,440,Happiny,Normal,0,220,100,5,5,15,65,30,4,False,220
296,273,Seedot,Grass,0,220,40,40,50,30,30,30,3,False,220
284,261,Poochyena,Dark,0,220,35,55,35,30,30,35,3,False,220
187,173,Cleffa,Fairy,0,218,50,25,28,45,55,15,2,False,218
175,161,Sentret,Normal,0,215,35,46,34,35,45,20,2,False,215
733,665,Spewpa,Bug,0,213,45,22,60,27,30,29,6,False,213
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False,210
188,174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False,210
255,236,Tyrogue,Fighting,0,210,35,35,35,35,35,35,2,False,210
186,172,Pichu,Electric,0,205,20,40,15,35,35,60,2,False,205
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,205
14,11,Metapod,Bug,0,205,50,20,55,25,25,30,1,False,205
289,266,Silcoon,Bug,0,205,50,35,55,25,25,15,3,False,205
291,268,Cascoon,Bug,0,205,50,35,55,25,25,15,3,False,205
139,129,Magikarp,Water,0,200,20,10,55,15,20,80,1,False,200
381,349,Feebas,Water,0,200,20,15,20,10,55,80,3,False,200
732,664,Scatterbug,Bug,0,200,38,35,40,27,25,35,6,False,200
303,280,Ralts,Psychic,Fairy,198,28,25,25,45,35,40,3,False,198
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,195
13,10,Caterpie,Bug,0,195,45,30,35,20,20,45,1,False,195
288,265,Wurmple,Bug,0,195,45,45,35,20,30,20,3,False,195
446,401,Kricketot,Bug,0,194,37,25,41,25,41,25,4,False,194
322,298,Azurill,Normal,Fairy,190,50,20,40,20,40,20,3,False,190
206,191,Sunkern,Grass,0,180,30,30,30,30,30,30,2,False,180